/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar cursos
         * @description Lista los cursos del tenant visibles para el usuario (docente ve los suyos, estudiante los matriculados). Paginación por cursor.
         */
        get: operations["listCourses"];
        put?: never;
        /**
         * Crear curso
         * @description Crea un curso en el tenant del docente autenticado (H1). Rol requerido `docente` o `admin_colegio`.
         */
        post: operations["createCourse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{courseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener curso
         * @description Devuelve un curso del tenant del usuario. Si pertenece a otro colegio responde 404.
         */
        get: operations["getCourse"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{courseId}/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Matricular estudiante
         * @description Matricula a un estudiante del mismo tenant por su correo institucional (H1). Si el estudiante pertenece a otro colegio, responde 404.
         */
        post: operations["enrollStudent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{courseId}/assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Crear evaluación
         * @description Crea una evaluación de alternativas en estado `draft` con retroalimentación por pregunta (H2).
         */
        post: operations["createAssessment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Publicar o cerrar evaluación
         * @description Cambia el estado de la evaluación (H2). No se puede publicar si alguna pregunta no tiene respuesta correcta (422).
         */
        patch: operations["updateAssessmentStatus"];
        trace?: never;
    };
    "/assessments/{assessmentId}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rendir evaluación
         * @description El estudiante envía sus respuestas y recibe puntaje y retroalimentación al instante (H4).
         *     Requiere estar matriculado (si no, 404). Un segundo envío responde 409 con el resultado anterior
         *     en `detail`. Reintentar con la misma `Idempotency-Key` devuelve la misma respuesta sin duplicar.
         */
        post: operations["submitAssessment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assessments/{assessmentId}/results": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard de resultados
         * @description Resultados agregados de la evaluación para el docente (H3). Sin respuestas devuelve `submissions_count = 0` y listas vacías (no error).
         */
        get: operations["getAssessmentResults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{courseId}/tutor-questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preguntar al tutor IA
         * @description Encola una pregunta al tutor IA del curso (H5). Se procesa de forma asíncrona (SQS + worker, ADR 0003).
         *     Responde 202 con la URL para consultar el estado. Solo se usan como fuente los apuntes del curso y tenant del estudiante.
         */
        post: operations["askTutor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tutor-questions/{questionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar respuesta del tutor IA
         * @description Devuelve el estado y, cuando está lista, la respuesta con sus fuentes. Si no hay contenido de respaldo, `grounded = false` y el tutor indica que no tiene información suficiente.
         */
        get: operations["getTutorQuestion"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Error RFC 7807. */
        Problem: {
            /**
             * Format: uri
             * @example https://api.aulaviva.example/errors/validation
             */
            type: string;
            /** @example Datos inválidos */
            title: string;
            /** @example 422 */
            status: number;
            /** @example La pregunta 2 no tiene respuesta correcta. */
            detail?: string;
            /** @example /v1/assessments/5f0c.../ */
            instance?: string;
            /** @example c8f2b1d4e7 */
            trace_id?: string;
            /** @description Detalle por campo (solo en 422). */
            errors?: {
                /** @example questions[1].correct_option */
                field: string;
                /** @example Requerido para publicar. */
                message: string;
            }[];
        };
        CourseInput: {
            /** @example Matemáticas 7° Básico A */
            name: string;
            /** @example 2026-S2 */
            period: string;
            /** @example Matemática */
            subject?: string;
            /** @example 7B */
            grade_level?: string;
        };
        Course: components["schemas"]["CourseInput"] & {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            teacher_id: string;
            students_count?: number;
            /** Format: date-time */
            created_at: string;
        };
        CoursePage: {
            data: components["schemas"]["Course"][];
            /** @description Cursor de la siguiente página; null si no hay más. */
            next_cursor?: string | null;
        };
        EnrollmentInput: {
            /**
             * Format: email
             * @example estudiante.demo@colegio-demo.cl
             */
            student_email: string;
        };
        Enrollment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            course_id: string;
            /** Format: uuid */
            student_id: string;
            /** Format: date-time */
            enrolled_at: string;
        };
        QuestionInput: {
            /** @example ¿Cuánto es 3/4 + 1/4? */
            statement: string;
            /**
             * @example [
             *       "1/2",
             *       "1",
             *       "4/8",
             *       "3/16"
             *     ]
             */
            options: string[];
            /**
             * @description Índice de la alternativa correcta. Obligatorio para publicar.
             * @example 1
             */
            correct_option?: number | null;
            /**
             * @description Retroalimentación que ve el estudiante tras responder.
             * @example Suma los numeradores con igual denominador: 4/4 = 1.
             */
            feedback?: string;
        };
        AssessmentInput: {
            /** @example Prueba de fracciones */
            title: string;
            /**
             * @description MVP: un intento.
             * @default 1
             */
            max_attempts: number;
            questions: components["schemas"]["QuestionInput"][];
        };
        Assessment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            course_id: string;
            title: string;
            /** @enum {string} */
            status: "draft" | "published" | "closed";
            max_attempts?: number;
            questions: (components["schemas"]["QuestionInput"] & {
                /** Format: uuid */
                id: string;
            })[];
            /** Format: date-time */
            published_at?: string | null;
        };
        AssessmentStatusInput: {
            /** @enum {string} */
            status: "published" | "closed";
        };
        SubmissionInput: {
            answers: {
                /** Format: uuid */
                question_id: string;
                selected_option: number;
            }[];
        };
        SubmissionResult: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            assessment_id: string;
            /** @example 8 */
            score: number;
            /** @example 10 */
            max_score: number;
            answers: {
                /** Format: uuid */
                question_id: string;
                correct: boolean;
                feedback: string;
            }[];
            /** Format: date-time */
            submitted_at: string;
        };
        AssessmentResults: {
            /** Format: uuid */
            assessment_id: string;
            submissions_count: number;
            /** @description null si no hay respuestas. */
            average_score: number | null;
            /** @description Porcentaje de aciertos por pregunta. */
            questions: {
                /** Format: uuid */
                question_id: string;
                correct_rate: number;
            }[];
            /** @description Detalle por estudiante (o solo uno si se filtra por `student_id`). */
            students?: {
                /** Format: uuid */
                student_id: string;
                score: number;
                /** Format: date-time */
                submitted_at?: string;
            }[];
        };
        TutorQuestionInput: {
            /** @example ¿Por qué 3/4 + 1/4 da 1? */
            question: string;
        };
        TutorQuestion: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            course_id: string;
            /** @enum {string} */
            status: "queued" | "answered" | "failed";
            question: string;
            answer?: string | null;
            /** @description true si la respuesta se basa en apuntes del curso; false si no hubo contenido de respaldo. */
            grounded?: boolean | null;
            /** @description Apuntes del curso usados como fuente (siempre del mismo tenant). */
            sources?: {
                /** Format: uuid */
                note_id: string;
                title: string;
            }[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            answered_at?: string | null;
        };
    };
    responses: {
        /** @description Solicitud mal formada (por ejemplo, falta Idempotency-Key). */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Token ausente o inválido. */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description El rol del usuario no permite la operación. */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description No existe en el tenant del usuario (también si pertenece a otro colegio). */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Conflicto de estado (ya matriculado, evaluación ya rendida). */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Datos inválidos según reglas de negocio. */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "type": "https://api.aulaviva.example/errors/validation",
                 *       "title": "Datos inválidos",
                 *       "status": 422,
                 *       "detail": "No se puede publicar: la pregunta 2 no tiene respuesta correcta.",
                 *       "instance": "/v1/assessments/3b1f7c1e-2a4d-4c1b-9d7e-0c5a1e2f3a4b",
                 *       "trace_id": "c8f2b1d4e7",
                 *       "errors": [
                 *         {
                 *           "field": "questions[1].correct_option",
                 *           "message": "Requerido para publicar."
                 *         }
                 *       ]
                 *     }
                 */
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Límite de solicitudes por tenant excedido (FinOps del LLM y protección en picos). */
        RateLimited: {
            headers: {
                "Retry-After": components["headers"]["Retry-After"];
                "X-RateLimit-Remaining": components["headers"]["X-RateLimit-Remaining"];
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        /** @description UUID generado por el cliente. Misma clave en 24 h = misma respuesta, sin duplicar. */
        IdempotencyKey: string;
        /** @description Identificador del curso. */
        CourseId: string;
        /** @description Identificador de la evaluación. */
        AssessmentId: string;
        /** @description Cursor opaco devuelto en `next_cursor`. */
        Cursor: string;
        /** @description Tamaño de página. */
        Limit: number;
    };
    requestBodies: never;
    headers: {
        /** @description Identificador de traza para correlacionar logs (CloudWatch). */
        "X-Trace-Id": string;
        /** @description Solicitudes restantes en la ventana para el tenant. */
        "X-RateLimit-Remaining": number;
        /** @description Segundos a esperar antes de reintentar. */
        "Retry-After": number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listCourses: {
        parameters: {
            query?: {
                /** @description Cursor opaco devuelto en `next_cursor`. */
                cursor?: components["parameters"]["Cursor"];
                /** @description Tamaño de página. */
                limit?: components["parameters"]["Limit"];
                /** @description Filtra por periodo académico. */
                period?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de cursos. */
            200: {
                headers: {
                    "X-Trace-Id": components["headers"]["X-Trace-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoursePage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["RateLimited"];
        };
    };
    createCourse: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID generado por el cliente. Misma clave en 24 h = misma respuesta, sin duplicar. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseInput"];
            };
        };
        responses: {
            /** @description Curso creado. */
            201: {
                headers: {
                    /** @description URL del curso creado. */
                    Location?: string;
                    "X-Trace-Id": components["headers"]["X-Trace-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    getCourse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador del curso. */
                courseId: components["parameters"]["CourseId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Curso. */
            200: {
                headers: {
                    "X-Trace-Id": components["headers"]["X-Trace-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Course"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    enrollStudent: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID generado por el cliente. Misma clave en 24 h = misma respuesta, sin duplicar. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                /** @description Identificador del curso. */
                courseId: components["parameters"]["CourseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollmentInput"];
            };
        };
        responses: {
            /** @description Estudiante matriculado. */
            201: {
                headers: {
                    "X-Trace-Id": components["headers"]["X-Trace-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Enrollment"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
        };
    };
    createAssessment: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID generado por el cliente. Misma clave en 24 h = misma respuesta, sin duplicar. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                /** @description Identificador del curso. */
                courseId: components["parameters"]["CourseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssessmentInput"];
            };
        };
        responses: {
            /** @description Evaluación creada en borrador. */
            201: {
                headers: {
                    "X-Trace-Id": components["headers"]["X-Trace-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assessment"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    updateAssessmentStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la evaluación. */
                assessmentId: components["parameters"]["AssessmentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssessmentStatusInput"];
            };
        };
        responses: {
            /** @description Evaluación actualizada. */
            200: {
                headers: {
                    "X-Trace-Id": components["headers"]["X-Trace-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assessment"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
        };
    };
    submitAssessment: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID generado por el cliente. Misma clave en 24 h = misma respuesta, sin duplicar. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                /** @description Identificador de la evaluación. */
                assessmentId: components["parameters"]["AssessmentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmissionInput"];
            };
        };
        responses: {
            /** @description Respuestas registradas y corregidas. */
            201: {
                headers: {
                    "X-Trace-Id": components["headers"]["X-Trace-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionResult"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    getAssessmentResults: {
        parameters: {
            query?: {
                /** @description Filtra el detalle por estudiante. */
                student_id?: string;
            };
            header?: never;
            path: {
                /** @description Identificador de la evaluación. */
                assessmentId: components["parameters"]["AssessmentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resultados agregados. */
            200: {
                headers: {
                    "X-Trace-Id": components["headers"]["X-Trace-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentResults"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    askTutor: {
        parameters: {
            query?: never;
            header: {
                /** @description UUID generado por el cliente. Misma clave en 24 h = misma respuesta, sin duplicar. */
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                /** @description Identificador del curso. */
                courseId: components["parameters"]["CourseId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TutorQuestionInput"];
            };
        };
        responses: {
            /** @description Pregunta aceptada y encolada. */
            202: {
                headers: {
                    /** @description URL para consultar la respuesta. */
                    Location?: string;
                    "X-Trace-Id": components["headers"]["X-Trace-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TutorQuestion"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            429: components["responses"]["RateLimited"];
        };
    };
    getTutorQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador de la pregunta. */
                questionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Estado de la pregunta. */
            200: {
                headers: {
                    "X-Trace-Id": components["headers"]["X-Trace-Id"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TutorQuestion"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
